---
title: Creative Computing
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: pretty
tagline: 
url: http://bsk.education/SE8_p5js
paginate: 1
baseurl: "/SE8_p5js"
sass:
  sass_dir: _sass
  style: :compressed
author:
  name: Ben Samuels-Kalow
  url: http://bsk.education
  email: bsk@ms224.org
version: 2.0.0
github:
  repo: https://github.com/bensk
gems:
- jemoji
- jekyll-archives
- jekyll-paginate
jekyll-archives:
  enabled: []
  layout: archive
  permalinks:
    year: "/:year/"
    month: "/:year/:month/"
    day: "/:year/:month/:day/"
    tag: "/tag/:name/"
    category: "/category/:name/"
future: true
